### ISSUE TITLE
AccountNavigation.spec.ts breaks randomly on cy.click()

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-mirror-node-explorer#195]
### Description

Test case "should follow links from account with few tokens"
 in AccountNavigation.spec.ts test breaks randomly on the same test case with the same message:

`CypressError: Timed out retrying after 8050ms: cy.click() failed because this element is detached from the DOM.`

This breakage occurs when test is run on GitHub. 

Full message:

`<td scoped="" class="o-table__td" data-label="ID">...</td>`

`Cypress requires elements be attached in the DOM to interact with them.`

`The previous command that ran was:`

  `> cy.eq()`

`This DOM element likely became detached somewhere between the previous and current command.`

`Common situations why this happens:`
`  - Your JS framework re-rendered asynchronously`
`  - Your app code reacted to an event firing and removed the element`

`You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.`

`https://on.cypress.io/element-has-detached-from-dom`
`      at $Cy.ensureAttached (http://localhost:38920/__cypress/runner/cypress_runner.js:167985:76)`
`      at runAllChecks (http://localhost:38920/__cypress/runner/cypress_runner.js:154413:12)`
`      at retryActionability (http://localhost:38920/__cypress/runner/cypress_runner.js:154493:16)`
`     at tryCatcher (http://localhost:38920/__cypress/runner/cypress_runner.js:13022:23)`
`      at Promise.attempt.Promise.try (http://localhost:38920/__cypress/runner/cypress_runner.js:10296:29)`
`      at whenStable (http://localhost:38920/__cypress/runner/cypress_runner.js:173538:65)`
`      at http://localhost:38920/__cypress/runner/cypress_runner.js:172993:14`
`      at tryCatcher (http://localhost:38920/__cypress/runner/cypress_runner.js:13022:23)`
`      at Promise._settlePromiseFromHandler (http://localhost:38920/__cypress/runner/cypress_runner.js:10957:31)`
`      at Promise._settlePromise (http://localhost:38920/__cypress/runner/cypress_runner.js:11014:18)`
`      at Promise._settlePromise0 (http://localhost:38920/__cypress/runner/cypress_runner.js:11059:10)`
`      at Promise._settlePromises (http://localhost:38920/__cypress/runner/cypress_runner.js:11139:18)`
`      at Promise._fulfill (http://localhost:38920/__cypress/runner/cypress_runner.js:11083:18)`
`      at http://localhost:38920/__cypress/runner/cypress_runner.js:12697:46`
`  From Your Spec Code:`
`      at Context.eval (http://localhost:38920/__cypress/tests?p=tests/e2e/specs/AccountNavigation.spec.ts:735:14)`

### Steps to reproduce

Runs `Hedera Mirror Node Explorer End-to-end Tests` action from GitHub env.

### Hedera network

other

### Version

Built Mon, 29 Aug 2022 16:06:12 GMT

**Comment by ericleponner** [comment]
This is fixed by https://github.com/hashgraph/hedera-mirror-node-explorer/pull/504
